/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CatalogItemMetadataEntryObservation struct {

	// Domain for this metadata entry. true if it belongs to SYSTEM, false if it belongs to GENERAL
	IsSystem *bool `json:"isSystem,omitempty" tf:"is_system,omitempty"`

	// Key of this metadata entry. Required if the metadata entry is not empty
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Type of this metadata entry. One of: 'MetadataStringValue', 'MetadataNumberValue', 'MetadataBooleanValue', 'MetadataDateTimeValue'
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// User access level for this metadata entry. One of: 'READWRITE', 'READONLY', 'PRIVATE'
	UserAccess *string `json:"userAccess,omitempty" tf:"user_access,omitempty"`

	// Value of this metadata entry. Required if the metadata entry is not empty
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type CatalogItemMetadataEntryParameters struct {

	// Domain for this metadata entry. true if it belongs to SYSTEM, false if it belongs to GENERAL
	// +kubebuilder:validation:Optional
	IsSystem *bool `json:"isSystem,omitempty" tf:"is_system,omitempty"`

	// Key of this metadata entry. Required if the metadata entry is not empty
	// +kubebuilder:validation:Optional
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// Type of this metadata entry. One of: 'MetadataStringValue', 'MetadataNumberValue', 'MetadataBooleanValue', 'MetadataDateTimeValue'
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// User access level for this metadata entry. One of: 'READWRITE', 'READONLY', 'PRIVATE'
	// +kubebuilder:validation:Optional
	UserAccess *string `json:"userAccess,omitempty" tf:"user_access,omitempty"`

	// Value of this metadata entry. Required if the metadata entry is not empty
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type CatalogItemObservation struct {

	// catalog name where upload the OVA file
	Catalog *string `json:"catalog,omitempty" tf:"catalog,omitempty"`

	// Key and value pairs for catalog item metadata
	CatalogItemMetadata map[string]*string `json:"catalogItemMetadata,omitempty" tf:"catalog_item_metadata,omitempty"`

	// Time stamp of when the item was created
	Created *string `json:"created,omitempty" tf:"created,omitempty"`

	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Key and value pairs for the metadata of the vApp template associated to this catalog item
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Metadata entries for the given Catalog Item
	MetadataEntry []CatalogItemMetadataEntryObservation `json:"metadataEntry,omitempty" tf:"metadata_entry,omitempty"`

	// catalog item name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Absolute or relative path to OVA
	OvaPath *string `json:"ovaPath,omitempty" tf:"ova_path,omitempty"`

	// URL of OVF file
	OvfURL *string `json:"ovfUrl,omitempty" tf:"ovf_url,omitempty"`

	// shows upload progress in stdout
	ShowUploadProgress *bool `json:"showUploadProgress,omitempty" tf:"show_upload_progress,omitempty"`

	// size of upload file piece size in mega bytes
	UploadPieceSize *float64 `json:"uploadPieceSize,omitempty" tf:"upload_piece_size,omitempty"`
}

type CatalogItemParameters struct {

	// catalog name where upload the OVA file
	// +kubebuilder:validation:Optional
	Catalog *string `json:"catalog,omitempty" tf:"catalog,omitempty"`

	// Key and value pairs for catalog item metadata
	// +kubebuilder:validation:Optional
	CatalogItemMetadata map[string]*string `json:"catalogItemMetadata,omitempty" tf:"catalog_item_metadata,omitempty"`

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Key and value pairs for the metadata of the vApp template associated to this catalog item
	// +kubebuilder:validation:Optional
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Metadata entries for the given Catalog Item
	// +kubebuilder:validation:Optional
	MetadataEntry []CatalogItemMetadataEntryParameters `json:"metadataEntry,omitempty" tf:"metadata_entry,omitempty"`

	// catalog item name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Absolute or relative path to OVA
	// +kubebuilder:validation:Optional
	OvaPath *string `json:"ovaPath,omitempty" tf:"ova_path,omitempty"`

	// URL of OVF file
	// +kubebuilder:validation:Optional
	OvfURL *string `json:"ovfUrl,omitempty" tf:"ovf_url,omitempty"`

	// shows upload progress in stdout
	// +kubebuilder:validation:Optional
	ShowUploadProgress *bool `json:"showUploadProgress,omitempty" tf:"show_upload_progress,omitempty"`

	// size of upload file piece size in mega bytes
	// +kubebuilder:validation:Optional
	UploadPieceSize *float64 `json:"uploadPieceSize,omitempty" tf:"upload_piece_size,omitempty"`
}

// CatalogItemSpec defines the desired state of CatalogItem
type CatalogItemSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CatalogItemParameters `json:"forProvider"`
}

// CatalogItemStatus defines the observed state of CatalogItem.
type CatalogItemStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CatalogItemObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// CatalogItem is the Schema for the CatalogItems API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type CatalogItem struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.catalog)",message="catalog is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	Spec   CatalogItemSpec   `json:"spec"`
	Status CatalogItemStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CatalogItemList contains a list of CatalogItems
type CatalogItemList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CatalogItem `json:"items"`
}

// Repository type metadata.
var (
	CatalogItem_Kind             = "CatalogItem"
	CatalogItem_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CatalogItem_Kind}.String()
	CatalogItem_KindAPIVersion   = CatalogItem_Kind + "." + CRDGroupVersion.String()
	CatalogItem_GroupVersionKind = CRDGroupVersion.WithKind(CatalogItem_Kind)
)

func init() {
	SchemeBuilder.Register(&CatalogItem{}, &CatalogItemList{})
}
