/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ExternalNetworkObservation_2 struct {
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A list of IP scopes for the network
	IPScope []IPScopeObservation `json:"ipScope,omitempty" tf:"ip_scope,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies whether the network resources such as IP/MAC of router will be retained across deployments. Default is false.
	RetainNetInfoAcrossDeployments *bool `json:"retainNetInfoAcrossDeployments,omitempty" tf:"retain_net_info_across_deployments,omitempty"`

	// A list of port groups that back this network. Each referenced DV_PORTGROUP or NETWORK must exist on a vCenter server registered with the system.
	VsphereNetwork []VsphereNetworkObservation `json:"vsphereNetwork,omitempty" tf:"vsphere_network,omitempty"`
}

type ExternalNetworkParameters_2 struct {

	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A list of IP scopes for the network
	// +kubebuilder:validation:Optional
	IPScope []IPScopeParameters `json:"ipScope,omitempty" tf:"ip_scope,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies whether the network resources such as IP/MAC of router will be retained across deployments. Default is false.
	// +kubebuilder:validation:Optional
	RetainNetInfoAcrossDeployments *bool `json:"retainNetInfoAcrossDeployments,omitempty" tf:"retain_net_info_across_deployments,omitempty"`

	// A list of port groups that back this network. Each referenced DV_PORTGROUP or NETWORK must exist on a vCenter server registered with the system.
	// +kubebuilder:validation:Optional
	VsphereNetwork []VsphereNetworkParameters `json:"vsphereNetwork,omitempty" tf:"vsphere_network,omitempty"`
}

type IPScopeObservation struct {

	// DNS suffix
	DNSSuffix *string `json:"dnsSuffix,omitempty" tf:"dns_suffix,omitempty"`

	// Primary DNS server
	Dns1 *string `json:"dns1,omitempty" tf:"dns1,omitempty"`

	// Secondary DNS server
	Dns2 *string `json:"dns2,omitempty" tf:"dns2,omitempty"`

	// Gateway of the network
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// Network mask
	Netmask *string `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// IP ranges used for static pool allocation in the network
	StaticIPPool []StaticIPPoolObservation `json:"staticIpPool,omitempty" tf:"static_ip_pool,omitempty"`
}

type IPScopeParameters struct {

	// DNS suffix
	// +kubebuilder:validation:Optional
	DNSSuffix *string `json:"dnsSuffix,omitempty" tf:"dns_suffix,omitempty"`

	// Primary DNS server
	// +kubebuilder:validation:Optional
	Dns1 *string `json:"dns1,omitempty" tf:"dns1,omitempty"`

	// Secondary DNS server
	// +kubebuilder:validation:Optional
	Dns2 *string `json:"dns2,omitempty" tf:"dns2,omitempty"`

	// Gateway of the network
	// +kubebuilder:validation:Required
	Gateway *string `json:"gateway" tf:"gateway,omitempty"`

	// Network mask
	// +kubebuilder:validation:Required
	Netmask *string `json:"netmask" tf:"netmask,omitempty"`

	// IP ranges used for static pool allocation in the network
	// +kubebuilder:validation:Optional
	StaticIPPool []StaticIPPoolParameters `json:"staticIpPool,omitempty" tf:"static_ip_pool,omitempty"`
}

type StaticIPPoolObservation struct {

	// End address of the IP range
	EndAddress *string `json:"endAddress,omitempty" tf:"end_address,omitempty"`

	// Start address of the IP range
	StartAddress *string `json:"startAddress,omitempty" tf:"start_address,omitempty"`
}

type StaticIPPoolParameters struct {

	// End address of the IP range
	// +kubebuilder:validation:Required
	EndAddress *string `json:"endAddress" tf:"end_address,omitempty"`

	// Start address of the IP range
	// +kubebuilder:validation:Required
	StartAddress *string `json:"startAddress" tf:"start_address,omitempty"`
}

type VsphereNetworkObservation struct {

	// The name of the port group
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The vSphere port group type. One of: DV_PORTGROUP (distributed virtual port group), NETWORK
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The vCenter server name
	Vcenter *string `json:"vcenter,omitempty" tf:"vcenter,omitempty"`
}

type VsphereNetworkParameters struct {

	// The name of the port group
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// The vSphere port group type. One of: DV_PORTGROUP (distributed virtual port group), NETWORK
	// +kubebuilder:validation:Required
	Type *string `json:"type" tf:"type,omitempty"`

	// The vCenter server name
	// +kubebuilder:validation:Required
	Vcenter *string `json:"vcenter" tf:"vcenter,omitempty"`
}

// ExternalNetworkSpec defines the desired state of ExternalNetwork
type ExternalNetworkSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ExternalNetworkParameters_2 `json:"forProvider"`
}

// ExternalNetworkStatus defines the observed state of ExternalNetwork.
type ExternalNetworkStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ExternalNetworkObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// ExternalNetwork is the Schema for the ExternalNetworks API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type ExternalNetwork struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.ipScope)",message="ipScope is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.vsphereNetwork)",message="vsphereNetwork is a required parameter"
	Spec   ExternalNetworkSpec   `json:"spec"`
	Status ExternalNetworkStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExternalNetworkList contains a list of ExternalNetworks
type ExternalNetworkList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ExternalNetwork `json:"items"`
}

// Repository type metadata.
var (
	ExternalNetwork_Kind             = "ExternalNetwork"
	ExternalNetwork_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ExternalNetwork_Kind}.String()
	ExternalNetwork_KindAPIVersion   = ExternalNetwork_Kind + "." + CRDGroupVersion.String()
	ExternalNetwork_GroupVersionKind = CRDGroupVersion.WithKind(ExternalNetwork_Kind)
)

func init() {
	SchemeBuilder.Register(&ExternalNetwork{}, &ExternalNetworkList{})
}
