/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type LbVirtualServerObservation struct {

	// Application profile ID to be associated with the virtual server
	AppProfileID *string `json:"appProfileId,omitempty" tf:"app_profile_id,omitempty"`

	// List of attached application rule IDs
	AppRuleIds []*string `json:"appRuleIds,omitempty" tf:"app_rule_ids,omitempty"`

	// Maximum concurrent connections that the virtual server can process
	ConnectionLimit *float64 `json:"connectionLimit,omitempty" tf:"connection_limit,omitempty"`

	// Maximum incoming new connection requests per second
	ConnectionRateLimit *float64 `json:"connectionRateLimit,omitempty" tf:"connection_rate_limit,omitempty"`

	// Virtual Server description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Edge gateway name in which the LB Virtual Server is located
	EdgeGateway *string `json:"edgeGateway,omitempty" tf:"edge_gateway,omitempty"`

	// Enable virtual server acceleration
	EnableAcceleration *bool `json:"enableAcceleration,omitempty" tf:"enable_acceleration,omitempty"`

	// Defines if the virtual server is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IP address that the load balancer listens on
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// Unique Virtual Server name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Port number that the load balancer listens on
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Protocol that the virtual server accepts
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The server pool that the load balancer will use
	ServerPoolID *string `json:"serverPoolId,omitempty" tf:"server_pool_id,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type LbVirtualServerParameters struct {

	// Application profile ID to be associated with the virtual server
	// +kubebuilder:validation:Optional
	AppProfileID *string `json:"appProfileId,omitempty" tf:"app_profile_id,omitempty"`

	// List of attached application rule IDs
	// +kubebuilder:validation:Optional
	AppRuleIds []*string `json:"appRuleIds,omitempty" tf:"app_rule_ids,omitempty"`

	// Maximum concurrent connections that the virtual server can process
	// +kubebuilder:validation:Optional
	ConnectionLimit *float64 `json:"connectionLimit,omitempty" tf:"connection_limit,omitempty"`

	// Maximum incoming new connection requests per second
	// +kubebuilder:validation:Optional
	ConnectionRateLimit *float64 `json:"connectionRateLimit,omitempty" tf:"connection_rate_limit,omitempty"`

	// Virtual Server description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Edge gateway name in which the LB Virtual Server is located
	// +kubebuilder:validation:Optional
	EdgeGateway *string `json:"edgeGateway,omitempty" tf:"edge_gateway,omitempty"`

	// Enable virtual server acceleration
	// +kubebuilder:validation:Optional
	EnableAcceleration *bool `json:"enableAcceleration,omitempty" tf:"enable_acceleration,omitempty"`

	// Defines if the virtual server is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// IP address that the load balancer listens on
	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// Unique Virtual Server name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Port number that the load balancer listens on
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Protocol that the virtual server accepts
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The server pool that the load balancer will use
	// +kubebuilder:validation:Optional
	ServerPoolID *string `json:"serverPoolId,omitempty" tf:"server_pool_id,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	// +kubebuilder:validation:Optional
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

// LbVirtualServerSpec defines the desired state of LbVirtualServer
type LbVirtualServerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LbVirtualServerParameters `json:"forProvider"`
}

// LbVirtualServerStatus defines the observed state of LbVirtualServer.
type LbVirtualServerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LbVirtualServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// LbVirtualServer is the Schema for the LbVirtualServers API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type LbVirtualServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.edgeGateway)",message="edgeGateway is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.ipAddress)",message="ipAddress is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.port)",message="port is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.protocol)",message="protocol is a required parameter"
	Spec   LbVirtualServerSpec   `json:"spec"`
	Status LbVirtualServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LbVirtualServerList contains a list of LbVirtualServers
type LbVirtualServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LbVirtualServer `json:"items"`
}

// Repository type metadata.
var (
	LbVirtualServer_Kind             = "LbVirtualServer"
	LbVirtualServer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LbVirtualServer_Kind}.String()
	LbVirtualServer_KindAPIVersion   = LbVirtualServer_Kind + "." + CRDGroupVersion.String()
	LbVirtualServer_GroupVersionKind = CRDGroupVersion.WithKind(LbVirtualServer_Kind)
)

func init() {
	SchemeBuilder.Register(&LbVirtualServer{}, &LbVirtualServerList{})
}
