/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type NsxtDistributedFirewallRuleObservation struct {

	// An optional firewall rule ID, to put new rule above during creation
	AboveRuleID *string `json:"aboveRuleId,omitempty" tf:"above_rule_id,omitempty"`

	// Defines if the rule should 'ALLOW', 'DROP', 'REJECT' matching traffic
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// A set of Application Port Profile IDs. Leaving it empty means 'Any'
	AppPortProfileIds []*string `json:"appPortProfileIds,omitempty" tf:"app_port_profile_ids,omitempty"`

	// Comment that is shown next to rule in UI (VCD 10.3.2+)
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Description is not shown in UI
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Reverses firewall matching for to match all except Destinations Groups specified in 'destination_ids' (VCD 10.3.2+)
	DestinationGroupsExcluded *bool `json:"destinationGroupsExcluded,omitempty" tf:"destination_groups_excluded,omitempty"`

	// A set of Destination Firewall Group IDs (IP Sets or Security Groups). Leaving it empty means 'Any'
	DestinationIds []*string `json:"destinationIds,omitempty" tf:"destination_ids,omitempty"`

	// Direction on which Firewall Rule applies (one of 'IN', 'OUT', 'IN_OUT')
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// Defined if Firewall Rule is active
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Firewall Rule Protocol (one of 'IPV4', 'IPV6', 'IPV4_IPV6')
	IPProtocol *string `json:"ipProtocol,omitempty" tf:"ip_protocol,omitempty"`

	// Defines if matching traffic should be logged
	Logging *bool `json:"logging,omitempty" tf:"logging,omitempty"`

	// Firewall Rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of Network Context Profile IDs. Leaving it empty means 'Any'
	NetworkContextProfileIds []*string `json:"networkContextProfileIds,omitempty" tf:"network_context_profile_ids,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Reverses firewall matching for to match all except Source Groups specified in 'source_ids' (VCD 10.3.2+)
	SourceGroupsExcluded *bool `json:"sourceGroupsExcluded,omitempty" tf:"source_groups_excluded,omitempty"`

	// A set of Source Firewall Group IDs (IP Sets or Security Groups). Leaving it empty means 'Any'
	SourceIds []*string `json:"sourceIds,omitempty" tf:"source_ids,omitempty"`

	// ID of VDC Group for Distributed Firewall
	VdcGroupID *string `json:"vdcGroupId,omitempty" tf:"vdc_group_id,omitempty"`
}

type NsxtDistributedFirewallRuleParameters struct {

	// An optional firewall rule ID, to put new rule above during creation
	// +kubebuilder:validation:Optional
	AboveRuleID *string `json:"aboveRuleId,omitempty" tf:"above_rule_id,omitempty"`

	// Defines if the rule should 'ALLOW', 'DROP', 'REJECT' matching traffic
	// +kubebuilder:validation:Optional
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// A set of Application Port Profile IDs. Leaving it empty means 'Any'
	// +kubebuilder:validation:Optional
	AppPortProfileIds []*string `json:"appPortProfileIds,omitempty" tf:"app_port_profile_ids,omitempty"`

	// Comment that is shown next to rule in UI (VCD 10.3.2+)
	// +kubebuilder:validation:Optional
	Comment *string `json:"comment,omitempty" tf:"comment,omitempty"`

	// Description is not shown in UI
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Reverses firewall matching for to match all except Destinations Groups specified in 'destination_ids' (VCD 10.3.2+)
	// +kubebuilder:validation:Optional
	DestinationGroupsExcluded *bool `json:"destinationGroupsExcluded,omitempty" tf:"destination_groups_excluded,omitempty"`

	// A set of Destination Firewall Group IDs (IP Sets or Security Groups). Leaving it empty means 'Any'
	// +kubebuilder:validation:Optional
	DestinationIds []*string `json:"destinationIds,omitempty" tf:"destination_ids,omitempty"`

	// Direction on which Firewall Rule applies (one of 'IN', 'OUT', 'IN_OUT')
	// +kubebuilder:validation:Optional
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// Defined if Firewall Rule is active
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Firewall Rule Protocol (one of 'IPV4', 'IPV6', 'IPV4_IPV6')
	// +kubebuilder:validation:Optional
	IPProtocol *string `json:"ipProtocol,omitempty" tf:"ip_protocol,omitempty"`

	// Defines if matching traffic should be logged
	// +kubebuilder:validation:Optional
	Logging *bool `json:"logging,omitempty" tf:"logging,omitempty"`

	// Firewall Rule name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of Network Context Profile IDs. Leaving it empty means 'Any'
	// +kubebuilder:validation:Optional
	NetworkContextProfileIds []*string `json:"networkContextProfileIds,omitempty" tf:"network_context_profile_ids,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Reverses firewall matching for to match all except Source Groups specified in 'source_ids' (VCD 10.3.2+)
	// +kubebuilder:validation:Optional
	SourceGroupsExcluded *bool `json:"sourceGroupsExcluded,omitempty" tf:"source_groups_excluded,omitempty"`

	// A set of Source Firewall Group IDs (IP Sets or Security Groups). Leaving it empty means 'Any'
	// +kubebuilder:validation:Optional
	SourceIds []*string `json:"sourceIds,omitempty" tf:"source_ids,omitempty"`

	// ID of VDC Group for Distributed Firewall
	// +kubebuilder:validation:Optional
	VdcGroupID *string `json:"vdcGroupId,omitempty" tf:"vdc_group_id,omitempty"`
}

// NsxtDistributedFirewallRuleSpec defines the desired state of NsxtDistributedFirewallRule
type NsxtDistributedFirewallRuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NsxtDistributedFirewallRuleParameters `json:"forProvider"`
}

// NsxtDistributedFirewallRuleStatus defines the observed state of NsxtDistributedFirewallRule.
type NsxtDistributedFirewallRuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NsxtDistributedFirewallRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// NsxtDistributedFirewallRule is the Schema for the NsxtDistributedFirewallRules API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type NsxtDistributedFirewallRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.action)",message="action is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.vdcGroupId)",message="vdcGroupId is a required parameter"
	Spec   NsxtDistributedFirewallRuleSpec   `json:"spec"`
	Status NsxtDistributedFirewallRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NsxtDistributedFirewallRuleList contains a list of NsxtDistributedFirewallRules
type NsxtDistributedFirewallRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NsxtDistributedFirewallRule `json:"items"`
}

// Repository type metadata.
var (
	NsxtDistributedFirewallRule_Kind             = "NsxtDistributedFirewallRule"
	NsxtDistributedFirewallRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NsxtDistributedFirewallRule_Kind}.String()
	NsxtDistributedFirewallRule_KindAPIVersion   = NsxtDistributedFirewallRule_Kind + "." + CRDGroupVersion.String()
	NsxtDistributedFirewallRule_GroupVersionKind = CRDGroupVersion.WithKind(NsxtDistributedFirewallRule_Kind)
)

func init() {
	SchemeBuilder.Register(&NsxtDistributedFirewallRule{}, &NsxtDistributedFirewallRuleList{})
}
