/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ApplicationObservation struct {

	// Destination port for this application. Leaving it empty means 'any' port
	DestinationPort *string `json:"destinationPort,omitempty" tf:"destination_port,omitempty"`

	// Name of application (Application, ApplicationGroup)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Protocol of the application (one of TCP, UDP, ICMP) (When not using name/value)
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Source port for this application. Leaving it empty means 'any' port
	SourcePort *string `json:"sourcePort,omitempty" tf:"source_port,omitempty"`

	// Type of application
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Value of the application
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ApplicationParameters struct {

	// Destination port for this application. Leaving it empty means 'any' port
	// +kubebuilder:validation:Optional
	DestinationPort *string `json:"destinationPort,omitempty" tf:"destination_port,omitempty"`

	// Name of application (Application, ApplicationGroup)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Protocol of the application (one of TCP, UDP, ICMP) (When not using name/value)
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// Source port for this application. Leaving it empty means 'any' port
	// +kubebuilder:validation:Optional
	SourcePort *string `json:"sourcePort,omitempty" tf:"source_port,omitempty"`

	// Type of application
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Value of the application
	// +kubebuilder:validation:Optional
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type AppliedToObservation struct {

	// Name of the applied-to entity
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Type of the applied-to entity (one of Network, Edge, VirtualMachine, IPSet, VDC, Ipv4Address)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Value of the applied-to entity
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type AppliedToParameters struct {

	// Name of the applied-to entity
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// Type of the applied-to entity (one of Network, Edge, VirtualMachine, IPSet, VDC, Ipv4Address)
	// +kubebuilder:validation:Required
	Type *string `json:"type" tf:"type,omitempty"`

	// Value of the applied-to entity
	// +kubebuilder:validation:Required
	Value *string `json:"value" tf:"value,omitempty"`
}

type DestinationObservation struct {

	// Name of the destination entity
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Type of the destination entity (one of Network, Edge, VirtualMachine, IpSet, VDC, Ipv4Address)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Value of the destination entity
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type DestinationParameters struct {

	// Name of the destination entity
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// Type of the destination entity (one of Network, Edge, VirtualMachine, IpSet, VDC, Ipv4Address)
	// +kubebuilder:validation:Required
	Type *string `json:"type" tf:"type,omitempty"`

	// Value of the destination entity
	// +kubebuilder:validation:Required
	Value *string `json:"value" tf:"value,omitempty"`
}

type NsxvDistributedFirewallObservation struct {

	// Shows whether the NSX-V distributed firewall is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Ordered list of distributed firewall rules
	Rule []NsxvDistributedFirewallRuleObservation `json:"rule,omitempty" tf:"rule,omitempty"`

	// The ID of VDC
	VdcID *string `json:"vdcId,omitempty" tf:"vdc_id,omitempty"`
}

type NsxvDistributedFirewallParameters struct {

	// Ordered list of distributed firewall rules
	// +kubebuilder:validation:Optional
	Rule []NsxvDistributedFirewallRuleParameters `json:"rule,omitempty" tf:"rule,omitempty"`

	// The ID of VDC
	// +kubebuilder:validation:Optional
	VdcID *string `json:"vdcId,omitempty" tf:"vdc_id,omitempty"`
}

type NsxvDistributedFirewallRuleObservation struct {

	// Action of the rule (allow, deny)
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// Application definitions for this rule. An empty value means 'any'
	Application []ApplicationObservation `json:"application,omitempty" tf:"application,omitempty"`

	// List of elements to which this rule applies
	AppliedTo []AppliedToObservation `json:"appliedTo,omitempty" tf:"applied_to,omitempty"`

	// List of destination traffic for this rule. An empty value means 'any'
	Destination []DestinationObservation `json:"destination,omitempty" tf:"destination,omitempty"`

	// Direction of the rule (in, out, inout)
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// Whether the rule is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// If true, the content of the destination elements is reversed
	ExcludeDestination *bool `json:"excludeDestination,omitempty" tf:"exclude_destination,omitempty"`

	// If true, the content of the source elements is reversed
	ExcludeSource *bool `json:"excludeSource,omitempty" tf:"exclude_source,omitempty"`

	// Firewall Rule ID
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`

	// Whether the rule traffic is logged
	Logged *bool `json:"logged,omitempty" tf:"logged,omitempty"`

	// Firewall Rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Packet type of the rule (any, ipv4, ipv6)
	PacketType *string `json:"packetType,omitempty" tf:"packet_type,omitempty"`

	// List of source traffic for this rule. An empty value means 'any'
	Source []SourceObservation `json:"source,omitempty" tf:"source,omitempty"`
}

type NsxvDistributedFirewallRuleParameters struct {

	// Action of the rule (allow, deny)
	// +kubebuilder:validation:Required
	Action *string `json:"action" tf:"action,omitempty"`

	// Application definitions for this rule. An empty value means 'any'
	// +kubebuilder:validation:Optional
	Application []ApplicationParameters `json:"application,omitempty" tf:"application,omitempty"`

	// List of elements to which this rule applies
	// +kubebuilder:validation:Required
	AppliedTo []AppliedToParameters `json:"appliedTo" tf:"applied_to,omitempty"`

	// List of destination traffic for this rule. An empty value means 'any'
	// +kubebuilder:validation:Optional
	Destination []DestinationParameters `json:"destination,omitempty" tf:"destination,omitempty"`

	// Direction of the rule (in, out, inout)
	// +kubebuilder:validation:Required
	Direction *string `json:"direction" tf:"direction,omitempty"`

	// Whether the rule is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// If true, the content of the destination elements is reversed
	// +kubebuilder:validation:Optional
	ExcludeDestination *bool `json:"excludeDestination,omitempty" tf:"exclude_destination,omitempty"`

	// If true, the content of the source elements is reversed
	// +kubebuilder:validation:Optional
	ExcludeSource *bool `json:"excludeSource,omitempty" tf:"exclude_source,omitempty"`

	// Whether the rule traffic is logged
	// +kubebuilder:validation:Optional
	Logged *bool `json:"logged,omitempty" tf:"logged,omitempty"`

	// Firewall Rule name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Packet type of the rule (any, ipv4, ipv6)
	// +kubebuilder:validation:Optional
	PacketType *string `json:"packetType,omitempty" tf:"packet_type,omitempty"`

	// List of source traffic for this rule. An empty value means 'any'
	// +kubebuilder:validation:Optional
	Source []SourceParameters `json:"source,omitempty" tf:"source,omitempty"`
}

type SourceObservation struct {

	// Name of the source entity
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Type of the source entity (one of Network, Edge, VirtualMachine, IpSet, VDC, Ipv4Address)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Value of the source entity
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type SourceParameters struct {

	// Name of the source entity
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// Type of the source entity (one of Network, Edge, VirtualMachine, IpSet, VDC, Ipv4Address)
	// +kubebuilder:validation:Required
	Type *string `json:"type" tf:"type,omitempty"`

	// Value of the source entity
	// +kubebuilder:validation:Required
	Value *string `json:"value" tf:"value,omitempty"`
}

// NsxvDistributedFirewallSpec defines the desired state of NsxvDistributedFirewall
type NsxvDistributedFirewallSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NsxvDistributedFirewallParameters `json:"forProvider"`
}

// NsxvDistributedFirewallStatus defines the observed state of NsxvDistributedFirewall.
type NsxvDistributedFirewallStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NsxvDistributedFirewallObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// NsxvDistributedFirewall is the Schema for the NsxvDistributedFirewalls API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type NsxvDistributedFirewall struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.vdcId)",message="vdcId is a required parameter"
	Spec   NsxvDistributedFirewallSpec   `json:"spec"`
	Status NsxvDistributedFirewallStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NsxvDistributedFirewallList contains a list of NsxvDistributedFirewalls
type NsxvDistributedFirewallList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NsxvDistributedFirewall `json:"items"`
}

// Repository type metadata.
var (
	NsxvDistributedFirewall_Kind             = "NsxvDistributedFirewall"
	NsxvDistributedFirewall_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NsxvDistributedFirewall_Kind}.String()
	NsxvDistributedFirewall_KindAPIVersion   = NsxvDistributedFirewall_Kind + "." + CRDGroupVersion.String()
	NsxvDistributedFirewall_GroupVersionKind = CRDGroupVersion.WithKind(NsxvDistributedFirewall_Kind)
)

func init() {
	SchemeBuilder.Register(&NsxvDistributedFirewall{}, &NsxvDistributedFirewallList{})
}
