/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type NsxtEdgeGatewayDhcpV6Observation struct {

	// A set of DNS Servers (only applicable for 'SLAAC' mode)
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// A set of domain names (only applicable for 'SLAAC' mode)
	DomainNames []*string `json:"domainNames,omitempty" tf:"domain_names,omitempty"`

	// Edge gateway ID for Rate limiting (DHCPv6) configuration
	EdgeGatewayID *string `json:"edgeGatewayId,omitempty" tf:"edge_gateway_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// DHCPv6 configuration mode. One of 'SLAAC', 'DHCPv6', 'DISABLED'
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`
}

type NsxtEdgeGatewayDhcpV6Parameters struct {

	// A set of DNS Servers (only applicable for 'SLAAC' mode)
	// +kubebuilder:validation:Optional
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// A set of domain names (only applicable for 'SLAAC' mode)
	// +kubebuilder:validation:Optional
	DomainNames []*string `json:"domainNames,omitempty" tf:"domain_names,omitempty"`

	// Edge gateway ID for Rate limiting (DHCPv6) configuration
	// +kubebuilder:validation:Optional
	EdgeGatewayID *string `json:"edgeGatewayId,omitempty" tf:"edge_gateway_id,omitempty"`

	// DHCPv6 configuration mode. One of 'SLAAC', 'DHCPv6', 'DISABLED'
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`
}

// NsxtEdgeGatewayDhcpV6Spec defines the desired state of NsxtEdgeGatewayDhcpV6
type NsxtEdgeGatewayDhcpV6Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NsxtEdgeGatewayDhcpV6Parameters `json:"forProvider"`
}

// NsxtEdgeGatewayDhcpV6Status defines the observed state of NsxtEdgeGatewayDhcpV6.
type NsxtEdgeGatewayDhcpV6Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NsxtEdgeGatewayDhcpV6Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// NsxtEdgeGatewayDhcpV6 is the Schema for the NsxtEdgeGatewayDhcpV6s API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type NsxtEdgeGatewayDhcpV6 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.edgeGatewayId)",message="edgeGatewayId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.mode)",message="mode is a required parameter"
	Spec   NsxtEdgeGatewayDhcpV6Spec   `json:"spec"`
	Status NsxtEdgeGatewayDhcpV6Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NsxtEdgeGatewayDhcpV6List contains a list of NsxtEdgeGatewayDhcpV6s
type NsxtEdgeGatewayDhcpV6List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NsxtEdgeGatewayDhcpV6 `json:"items"`
}

// Repository type metadata.
var (
	NsxtEdgeGatewayDhcpV6_Kind             = "NsxtEdgeGatewayDhcpV6"
	NsxtEdgeGatewayDhcpV6_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NsxtEdgeGatewayDhcpV6_Kind}.String()
	NsxtEdgeGatewayDhcpV6_KindAPIVersion   = NsxtEdgeGatewayDhcpV6_Kind + "." + CRDGroupVersion.String()
	NsxtEdgeGatewayDhcpV6_GroupVersionKind = CRDGroupVersion.WithKind(NsxtEdgeGatewayDhcpV6_Kind)
)

func init() {
	SchemeBuilder.Register(&NsxtEdgeGatewayDhcpV6{}, &NsxtEdgeGatewayDhcpV6List{})
}
