/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AppPortObservation struct {

	// Set of ports or ranges
	Port []*string `json:"port,omitempty" tf:"port,omitempty"`

	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`
}

type AppPortParameters struct {

	// Set of ports or ranges
	// +kubebuilder:validation:Optional
	Port []*string `json:"port,omitempty" tf:"port,omitempty"`

	// +kubebuilder:validation:Required
	Protocol *string `json:"protocol" tf:"protocol,omitempty"`
}

type NsxtAppPortProfileObservation struct {
	AppPort []AppPortObservation `json:"appPort,omitempty" tf:"app_port,omitempty"`

	// ID of VDC, VDC Group, or NSX-T Manager
	ContextID *string `json:"contextId,omitempty" tf:"context_id,omitempty"`

	// Application Port Profile description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Application Port Profile name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of NSX-T manager. Only required for 'PROVIDER' scope
	NsxtManagerID *string `json:"nsxtManagerId,omitempty" tf:"nsxt_manager_id,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Scope - 'PROVIDER' or 'TENANT'
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type NsxtAppPortProfileParameters struct {

	// +kubebuilder:validation:Optional
	AppPort []AppPortParameters `json:"appPort,omitempty" tf:"app_port,omitempty"`

	// ID of VDC, VDC Group, or NSX-T Manager
	// +kubebuilder:validation:Optional
	ContextID *string `json:"contextId,omitempty" tf:"context_id,omitempty"`

	// Application Port Profile description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Application Port Profile name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// ID of NSX-T manager. Only required for 'PROVIDER' scope
	// +kubebuilder:validation:Optional
	NsxtManagerID *string `json:"nsxtManagerId,omitempty" tf:"nsxt_manager_id,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Scope - 'PROVIDER' or 'TENANT'
	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	// +kubebuilder:validation:Optional
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

// NsxtAppPortProfileSpec defines the desired state of NsxtAppPortProfile
type NsxtAppPortProfileSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NsxtAppPortProfileParameters `json:"forProvider"`
}

// NsxtAppPortProfileStatus defines the observed state of NsxtAppPortProfile.
type NsxtAppPortProfileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NsxtAppPortProfileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// NsxtAppPortProfile is the Schema for the NsxtAppPortProfiles API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type NsxtAppPortProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.appPort)",message="appPort is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.scope)",message="scope is a required parameter"
	Spec   NsxtAppPortProfileSpec   `json:"spec"`
	Status NsxtAppPortProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NsxtAppPortProfileList contains a list of NsxtAppPortProfiles
type NsxtAppPortProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NsxtAppPortProfile `json:"items"`
}

// Repository type metadata.
var (
	NsxtAppPortProfile_Kind             = "NsxtAppPortProfile"
	NsxtAppPortProfile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NsxtAppPortProfile_Kind}.String()
	NsxtAppPortProfile_KindAPIVersion   = NsxtAppPortProfile_Kind + "." + CRDGroupVersion.String()
	NsxtAppPortProfile_GroupVersionKind = CRDGroupVersion.WithKind(NsxtAppPortProfile_Kind)
)

func init() {
	SchemeBuilder.Register(&NsxtAppPortProfile{}, &NsxtAppPortProfileList{})
}
