/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type DHCPV4ConfigObservation struct {

	// IPv4 gateway address
	GatewayIPAddress *string `json:"gatewayIpAddress,omitempty" tf:"gateway_ip_address,omitempty"`

	// Hostname for the DHCP client
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`
}

type DHCPV4ConfigParameters struct {

	// IPv4 gateway address
	// +kubebuilder:validation:Optional
	GatewayIPAddress *string `json:"gatewayIpAddress,omitempty" tf:"gateway_ip_address,omitempty"`

	// Hostname for the DHCP client
	// +kubebuilder:validation:Optional
	Hostname *string `json:"hostname,omitempty" tf:"hostname,omitempty"`
}

type DHCPV6ConfigObservation struct {

	// Set of domain names
	DomainNames []*string `json:"domainNames,omitempty" tf:"domain_names,omitempty"`

	// Set of SNTP servers
	SntpServers []*string `json:"sntpServers,omitempty" tf:"sntp_servers,omitempty"`
}

type DHCPV6ConfigParameters struct {

	// Set of domain names
	// +kubebuilder:validation:Optional
	DomainNames []*string `json:"domainNames,omitempty" tf:"domain_names,omitempty"`

	// Set of SNTP servers
	// +kubebuilder:validation:Optional
	SntpServers []*string `json:"sntpServers,omitempty" tf:"sntp_servers,omitempty"`
}

type NsxtNetworkDhcpBindingObservation struct {

	// Binding type 'IPV4' or 'IPV6'
	BindingType *string `json:"bindingType,omitempty" tf:"binding_type,omitempty"`

	// IPv4 specific DHCP Binding configuration
	DHCPV4Config []DHCPV4ConfigObservation `json:"dhcpV4Config,omitempty" tf:"dhcp_v4_config,omitempty"`

	// IPv6 specific DHCP Binding configuration
	DHCPV6Config []DHCPV6ConfigObservation `json:"dhcpV6Config,omitempty" tf:"dhcp_v6_config,omitempty"`

	// The DNS server IPs to be assigned . 2 values maximum.
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// Description of DHCP binding
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IP address of the DHCP binding
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// Lease time in seconds. Minimum value is 60 seconds
	LeaseTime *float64 `json:"leaseTime,omitempty" tf:"lease_time,omitempty"`

	// MAC address of the DHCP binding
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// Name of DHCP binding
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Parent Org VDC network ID
	OrgNetworkID *string `json:"orgNetworkId,omitempty" tf:"org_network_id,omitempty"`
}

type NsxtNetworkDhcpBindingParameters struct {

	// Binding type 'IPV4' or 'IPV6'
	// +kubebuilder:validation:Optional
	BindingType *string `json:"bindingType,omitempty" tf:"binding_type,omitempty"`

	// IPv4 specific DHCP Binding configuration
	// +kubebuilder:validation:Optional
	DHCPV4Config []DHCPV4ConfigParameters `json:"dhcpV4Config,omitempty" tf:"dhcp_v4_config,omitempty"`

	// IPv6 specific DHCP Binding configuration
	// +kubebuilder:validation:Optional
	DHCPV6Config []DHCPV6ConfigParameters `json:"dhcpV6Config,omitempty" tf:"dhcp_v6_config,omitempty"`

	// The DNS server IPs to be assigned . 2 values maximum.
	// +kubebuilder:validation:Optional
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// Description of DHCP binding
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// IP address of the DHCP binding
	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// Lease time in seconds. Minimum value is 60 seconds
	// +kubebuilder:validation:Optional
	LeaseTime *float64 `json:"leaseTime,omitempty" tf:"lease_time,omitempty"`

	// MAC address of the DHCP binding
	// +kubebuilder:validation:Optional
	MacAddress *string `json:"macAddress,omitempty" tf:"mac_address,omitempty"`

	// Name of DHCP binding
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Parent Org VDC network ID
	// +kubebuilder:validation:Optional
	OrgNetworkID *string `json:"orgNetworkId,omitempty" tf:"org_network_id,omitempty"`
}

// NsxtNetworkDhcpBindingSpec defines the desired state of NsxtNetworkDhcpBinding
type NsxtNetworkDhcpBindingSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NsxtNetworkDhcpBindingParameters `json:"forProvider"`
}

// NsxtNetworkDhcpBindingStatus defines the observed state of NsxtNetworkDhcpBinding.
type NsxtNetworkDhcpBindingStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NsxtNetworkDhcpBindingObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// NsxtNetworkDhcpBinding is the Schema for the NsxtNetworkDhcpBindings API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type NsxtNetworkDhcpBinding struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.bindingType)",message="bindingType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.ipAddress)",message="ipAddress is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.leaseTime)",message="leaseTime is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.macAddress)",message="macAddress is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.orgNetworkId)",message="orgNetworkId is a required parameter"
	Spec   NsxtNetworkDhcpBindingSpec   `json:"spec"`
	Status NsxtNetworkDhcpBindingStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NsxtNetworkDhcpBindingList contains a list of NsxtNetworkDhcpBindings
type NsxtNetworkDhcpBindingList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NsxtNetworkDhcpBinding `json:"items"`
}

// Repository type metadata.
var (
	NsxtNetworkDhcpBinding_Kind             = "NsxtNetworkDhcpBinding"
	NsxtNetworkDhcpBinding_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NsxtNetworkDhcpBinding_Kind}.String()
	NsxtNetworkDhcpBinding_KindAPIVersion   = NsxtNetworkDhcpBinding_Kind + "." + CRDGroupVersion.String()
	NsxtNetworkDhcpBinding_GroupVersionKind = CRDGroupVersion.WithKind(NsxtNetworkDhcpBinding_Kind)
)

func init() {
	SchemeBuilder.Register(&NsxtNetworkDhcpBinding{}, &NsxtNetworkDhcpBindingList{})
}
