/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type NsxvDhcpRelayObservation struct {

	// A set of IP domain names of DHCP servers
	DomainNames []*string `json:"domainNames,omitempty" tf:"domain_names,omitempty"`

	// Edge gateway name for DHCP relay settings
	EdgeGateway *string `json:"edgeGateway,omitempty" tf:"edge_gateway,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A set of IP address of DHCP servers
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// A set of IP set names which consist DHCP servers
	IPSets []*string `json:"ipSets,omitempty" tf:"ip_sets,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	RelayAgent []RelayAgentObservation `json:"relayAgent,omitempty" tf:"relay_agent,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type NsxvDhcpRelayParameters struct {

	// A set of IP domain names of DHCP servers
	// +kubebuilder:validation:Optional
	DomainNames []*string `json:"domainNames,omitempty" tf:"domain_names,omitempty"`

	// Edge gateway name for DHCP relay settings
	// +kubebuilder:validation:Optional
	EdgeGateway *string `json:"edgeGateway,omitempty" tf:"edge_gateway,omitempty"`

	// A set of IP address of DHCP servers
	// +kubebuilder:validation:Optional
	IPAddresses []*string `json:"ipAddresses,omitempty" tf:"ip_addresses,omitempty"`

	// A set of IP set names which consist DHCP servers
	// +kubebuilder:validation:Optional
	IPSets []*string `json:"ipSets,omitempty" tf:"ip_sets,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// +kubebuilder:validation:Optional
	RelayAgent []RelayAgentParameters `json:"relayAgent,omitempty" tf:"relay_agent,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	// +kubebuilder:validation:Optional
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type RelayAgentObservation struct {

	// Optional gateway IP address of org network which is to be used for relaying DHCP message to specified servers
	GatewayIPAddress *string `json:"gatewayIpAddress,omitempty" tf:"gateway_ip_address,omitempty"`

	// Org network which is to be used for relaying DHCP message to specified servers
	NetworkName *string `json:"networkName,omitempty" tf:"network_name,omitempty"`
}

type RelayAgentParameters struct {

	// Optional gateway IP address of org network which is to be used for relaying DHCP message to specified servers
	// +kubebuilder:validation:Optional
	GatewayIPAddress *string `json:"gatewayIpAddress,omitempty" tf:"gateway_ip_address,omitempty"`

	// Org network which is to be used for relaying DHCP message to specified servers
	// +kubebuilder:validation:Required
	NetworkName *string `json:"networkName" tf:"network_name,omitempty"`
}

// NsxvDhcpRelaySpec defines the desired state of NsxvDhcpRelay
type NsxvDhcpRelaySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NsxvDhcpRelayParameters `json:"forProvider"`
}

// NsxvDhcpRelayStatus defines the observed state of NsxvDhcpRelay.
type NsxvDhcpRelayStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NsxvDhcpRelayObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// NsxvDhcpRelay is the Schema for the NsxvDhcpRelays API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type NsxvDhcpRelay struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.edgeGateway)",message="edgeGateway is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.relayAgent)",message="relayAgent is a required parameter"
	Spec   NsxvDhcpRelaySpec   `json:"spec"`
	Status NsxvDhcpRelayStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NsxvDhcpRelayList contains a list of NsxvDhcpRelays
type NsxvDhcpRelayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NsxvDhcpRelay `json:"items"`
}

// Repository type metadata.
var (
	NsxvDhcpRelay_Kind             = "NsxvDhcpRelay"
	NsxvDhcpRelay_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NsxvDhcpRelay_Kind}.String()
	NsxvDhcpRelay_KindAPIVersion   = NsxvDhcpRelay_Kind + "." + CRDGroupVersion.String()
	NsxvDhcpRelay_GroupVersionKind = CRDGroupVersion.WithKind(NsxvDhcpRelay_Kind)
)

func init() {
	SchemeBuilder.Register(&NsxvDhcpRelay{}, &NsxvDhcpRelayList{})
}
