/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type NsxtFirewallObservation struct {

	// Edge Gateway ID in which Firewall Rule are located
	EdgeGatewayID *string `json:"edgeGatewayId,omitempty" tf:"edge_gateway_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Ordered list of firewall rules
	Rule []NsxtFirewallRuleObservation `json:"rule,omitempty" tf:"rule,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type NsxtFirewallParameters struct {

	// Edge Gateway ID in which Firewall Rule are located
	// +kubebuilder:validation:Optional
	EdgeGatewayID *string `json:"edgeGatewayId,omitempty" tf:"edge_gateway_id,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// Ordered list of firewall rules
	// +kubebuilder:validation:Optional
	Rule []NsxtFirewallRuleParameters `json:"rule,omitempty" tf:"rule,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	// +kubebuilder:validation:Optional
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type NsxtFirewallRuleObservation struct {

	// Defines if the rule should 'ALLOW' or 'DROP' matching traffic
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	// A set of Application Port Profile IDs. Leaving it empty means 'Any'
	AppPortProfileIds []*string `json:"appPortProfileIds,omitempty" tf:"app_port_profile_ids,omitempty"`

	// A set of Destination Firewall Group IDs (IP Sets or Security Groups). Leaving it empty means 'Any'
	DestinationIds []*string `json:"destinationIds,omitempty" tf:"destination_ids,omitempty"`

	// Direction on which Firewall Rule applies (One of 'IN', 'OUT', 'IN_OUT')
	Direction *string `json:"direction,omitempty" tf:"direction,omitempty"`

	// Defined if Firewall Rule is active
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Firewall Rule ID
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Firewall Rule Protocol (One of 'IPV4', 'IPV6', 'IPV4_IPV6')
	IPProtocol *string `json:"ipProtocol,omitempty" tf:"ip_protocol,omitempty"`

	// Defines if matching traffic should be logged
	Logging *bool `json:"logging,omitempty" tf:"logging,omitempty"`

	// Firewall Rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// A set of Source Firewall Group IDs (IP Sets or Security Groups). Leaving it empty means 'Any'
	SourceIds []*string `json:"sourceIds,omitempty" tf:"source_ids,omitempty"`
}

type NsxtFirewallRuleParameters struct {

	// Defines if the rule should 'ALLOW' or 'DROP' matching traffic
	// +kubebuilder:validation:Required
	Action *string `json:"action" tf:"action,omitempty"`

	// A set of Application Port Profile IDs. Leaving it empty means 'Any'
	// +kubebuilder:validation:Optional
	AppPortProfileIds []*string `json:"appPortProfileIds,omitempty" tf:"app_port_profile_ids,omitempty"`

	// A set of Destination Firewall Group IDs (IP Sets or Security Groups). Leaving it empty means 'Any'
	// +kubebuilder:validation:Optional
	DestinationIds []*string `json:"destinationIds,omitempty" tf:"destination_ids,omitempty"`

	// Direction on which Firewall Rule applies (One of 'IN', 'OUT', 'IN_OUT')
	// +kubebuilder:validation:Required
	Direction *string `json:"direction" tf:"direction,omitempty"`

	// Defined if Firewall Rule is active
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Firewall Rule Protocol (One of 'IPV4', 'IPV6', 'IPV4_IPV6')
	// +kubebuilder:validation:Required
	IPProtocol *string `json:"ipProtocol" tf:"ip_protocol,omitempty"`

	// Defines if matching traffic should be logged
	// +kubebuilder:validation:Optional
	Logging *bool `json:"logging,omitempty" tf:"logging,omitempty"`

	// Firewall Rule name
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// A set of Source Firewall Group IDs (IP Sets or Security Groups). Leaving it empty means 'Any'
	// +kubebuilder:validation:Optional
	SourceIds []*string `json:"sourceIds,omitempty" tf:"source_ids,omitempty"`
}

// NsxtFirewallSpec defines the desired state of NsxtFirewall
type NsxtFirewallSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NsxtFirewallParameters `json:"forProvider"`
}

// NsxtFirewallStatus defines the observed state of NsxtFirewall.
type NsxtFirewallStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NsxtFirewallObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// NsxtFirewall is the Schema for the NsxtFirewalls API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type NsxtFirewall struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.edgeGatewayId)",message="edgeGatewayId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.rule)",message="rule is a required parameter"
	Spec   NsxtFirewallSpec   `json:"spec"`
	Status NsxtFirewallStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NsxtFirewallList contains a list of NsxtFirewalls
type NsxtFirewallList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NsxtFirewall `json:"items"`
}

// Repository type metadata.
var (
	NsxtFirewall_Kind             = "NsxtFirewall"
	NsxtFirewall_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NsxtFirewall_Kind}.String()
	NsxtFirewall_KindAPIVersion   = NsxtFirewall_Kind + "." + CRDGroupVersion.String()
	NsxtFirewall_GroupVersionKind = CRDGroupVersion.WithKind(NsxtFirewall_Kind)
)

func init() {
	SchemeBuilder.Register(&NsxtFirewall{}, &NsxtFirewallList{})
}
