/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type OrgSamlObservation struct {

	// Optional email attribute name
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// Enable SAML authentication. When this option is set, authentication is deferred to the SAML identity provider
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Your service provider entity ID. Once you set this field, it cannot be changed back to empty.
	EntityID *string `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// Optional first name attribute name
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// Optional full name attribute name
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// Optional group attribute name
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the file containing the metadata from the identity provider
	IdentityProviderMetadataFile *string `json:"identityProviderMetadataFile,omitempty" tf:"identity_provider_metadata_file,omitempty"`

	// The text of the metadata from the identity provider
	IdentityProviderMetadataText *string `json:"identityProviderMetadataText,omitempty" tf:"identity_provider_metadata_text,omitempty"`

	// Organization ID
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Optional role attribute name
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// Optional surname attribute name
	Surname *string `json:"surname,omitempty" tf:"surname,omitempty"`

	// Optional username attribute name
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

type OrgSamlParameters struct {

	// Optional email attribute name
	// +kubebuilder:validation:Optional
	Email *string `json:"email,omitempty" tf:"email,omitempty"`

	// Enable SAML authentication. When this option is set, authentication is deferred to the SAML identity provider
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Your service provider entity ID. Once you set this field, it cannot be changed back to empty.
	// +kubebuilder:validation:Optional
	EntityID *string `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// Optional first name attribute name
	// +kubebuilder:validation:Optional
	FirstName *string `json:"firstName,omitempty" tf:"first_name,omitempty"`

	// Optional full name attribute name
	// +kubebuilder:validation:Optional
	FullName *string `json:"fullName,omitempty" tf:"full_name,omitempty"`

	// Optional group attribute name
	// +kubebuilder:validation:Optional
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// The name of the file containing the metadata from the identity provider
	// +kubebuilder:validation:Optional
	IdentityProviderMetadataFile *string `json:"identityProviderMetadataFile,omitempty" tf:"identity_provider_metadata_file,omitempty"`

	// The text of the metadata from the identity provider
	// +kubebuilder:validation:Optional
	IdentityProviderMetadataText *string `json:"identityProviderMetadataText,omitempty" tf:"identity_provider_metadata_text,omitempty"`

	// Organization ID
	// +kubebuilder:validation:Optional
	OrgID *string `json:"orgId,omitempty" tf:"org_id,omitempty"`

	// Optional role attribute name
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// Optional surname attribute name
	// +kubebuilder:validation:Optional
	Surname *string `json:"surname,omitempty" tf:"surname,omitempty"`

	// Optional username attribute name
	// +kubebuilder:validation:Optional
	UserName *string `json:"userName,omitempty" tf:"user_name,omitempty"`
}

// OrgSamlSpec defines the desired state of OrgSaml
type OrgSamlSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OrgSamlParameters `json:"forProvider"`
}

// OrgSamlStatus defines the observed state of OrgSaml.
type OrgSamlStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OrgSamlObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// OrgSaml is the Schema for the OrgSamls API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type OrgSaml struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.enabled)",message="enabled is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.orgId)",message="orgId is a required parameter"
	Spec   OrgSamlSpec   `json:"spec"`
	Status OrgSamlStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrgSamlList contains a list of OrgSamls
type OrgSamlList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrgSaml `json:"items"`
}

// Repository type metadata.
var (
	OrgSaml_Kind             = "OrgSaml"
	OrgSaml_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrgSaml_Kind}.String()
	OrgSaml_KindAPIVersion   = OrgSaml_Kind + "." + CRDGroupVersion.String()
	OrgSaml_GroupVersionKind = CRDGroupVersion.WithKind(OrgSaml_Kind)
)

func init() {
	SchemeBuilder.Register(&OrgSaml{}, &OrgSamlList{})
}
