/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RdeTypeBehaviorAclObservation struct {

	// Set of Access Level IDs to associate to the Behavior defined in `behavior_id` argument
	AccessLevelIds []*string `json:"accessLevelIds,omitempty" tf:"access_level_ids,omitempty"`

	// The ID of either a RDE Interface Behavior or RDE Type Behavior
	BehaviorID *string `json:"behaviorId,omitempty" tf:"behavior_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the RDE Type
	RdeTypeID *string `json:"rdeTypeId,omitempty" tf:"rde_type_id,omitempty"`
}

type RdeTypeBehaviorAclParameters struct {

	// Set of Access Level IDs to associate to the Behavior defined in `behavior_id` argument
	// +kubebuilder:validation:Optional
	AccessLevelIds []*string `json:"accessLevelIds,omitempty" tf:"access_level_ids,omitempty"`

	// The ID of either a RDE Interface Behavior or RDE Type Behavior
	// +kubebuilder:validation:Optional
	BehaviorID *string `json:"behaviorId,omitempty" tf:"behavior_id,omitempty"`

	// The ID of the RDE Type
	// +kubebuilder:validation:Optional
	RdeTypeID *string `json:"rdeTypeId,omitempty" tf:"rde_type_id,omitempty"`
}

// RdeTypeBehaviorAclSpec defines the desired state of RdeTypeBehaviorAcl
type RdeTypeBehaviorAclSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RdeTypeBehaviorAclParameters `json:"forProvider"`
}

// RdeTypeBehaviorAclStatus defines the observed state of RdeTypeBehaviorAcl.
type RdeTypeBehaviorAclStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RdeTypeBehaviorAclObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// RdeTypeBehaviorAcl is the Schema for the RdeTypeBehaviorAcls API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type RdeTypeBehaviorAcl struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.accessLevelIds)",message="accessLevelIds is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.behaviorId)",message="behaviorId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.rdeTypeId)",message="rdeTypeId is a required parameter"
	Spec   RdeTypeBehaviorAclSpec   `json:"spec"`
	Status RdeTypeBehaviorAclStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RdeTypeBehaviorAclList contains a list of RdeTypeBehaviorAcls
type RdeTypeBehaviorAclList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RdeTypeBehaviorAcl `json:"items"`
}

// Repository type metadata.
var (
	RdeTypeBehaviorAcl_Kind             = "RdeTypeBehaviorAcl"
	RdeTypeBehaviorAcl_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RdeTypeBehaviorAcl_Kind}.String()
	RdeTypeBehaviorAcl_KindAPIVersion   = RdeTypeBehaviorAcl_Kind + "." + CRDGroupVersion.String()
	RdeTypeBehaviorAcl_GroupVersionKind = CRDGroupVersion.WithKind(RdeTypeBehaviorAcl_Kind)
)

func init() {
	SchemeBuilder.Register(&RdeTypeBehaviorAcl{}, &RdeTypeBehaviorAclList{})
}
