/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RightsBundleObservation struct {

	// Key used for internationalization
	BundleKey *string `json:"bundleKey,omitempty" tf:"bundle_key,omitempty"`

	// Rights bundle description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of rights bundle.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When true, publishes the rights bundle to all tenants
	PublishToAllTenants *bool `json:"publishToAllTenants,omitempty" tf:"publish_to_all_tenants,omitempty"`

	// Whether this rights bundle is read-only
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// Set of rights assigned to this rights bundle
	Rights []*string `json:"rights,omitempty" tf:"rights,omitempty"`

	// Set of tenants to which this rights bundle is published
	Tenants []*string `json:"tenants,omitempty" tf:"tenants,omitempty"`
}

type RightsBundleParameters struct {

	// Rights bundle description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Name of rights bundle.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// When true, publishes the rights bundle to all tenants
	// +kubebuilder:validation:Optional
	PublishToAllTenants *bool `json:"publishToAllTenants,omitempty" tf:"publish_to_all_tenants,omitempty"`

	// Set of rights assigned to this rights bundle
	// +kubebuilder:validation:Optional
	Rights []*string `json:"rights,omitempty" tf:"rights,omitempty"`

	// Set of tenants to which this rights bundle is published
	// +kubebuilder:validation:Optional
	Tenants []*string `json:"tenants,omitempty" tf:"tenants,omitempty"`
}

// RightsBundleSpec defines the desired state of RightsBundle
type RightsBundleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RightsBundleParameters `json:"forProvider"`
}

// RightsBundleStatus defines the observed state of RightsBundle.
type RightsBundleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RightsBundleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// RightsBundle is the Schema for the RightsBundles API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type RightsBundle struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.description)",message="description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.name)",message="name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.publishToAllTenants)",message="publishToAllTenants is a required parameter"
	Spec   RightsBundleSpec   `json:"spec"`
	Status RightsBundleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RightsBundleList contains a list of RightsBundles
type RightsBundleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RightsBundle `json:"items"`
}

// Repository type metadata.
var (
	RightsBundle_Kind             = "RightsBundle"
	RightsBundle_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RightsBundle_Kind}.String()
	RightsBundle_KindAPIVersion   = RightsBundle_Kind + "." + CRDGroupVersion.String()
	RightsBundle_GroupVersionKind = CRDGroupVersion.WithKind(RightsBundle_Kind)
)

func init() {
	SchemeBuilder.Register(&RightsBundle{}, &RightsBundleList{})
}
