/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type UiPluginObservation struct {

	// The description of the UI Plugin
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// true to make the UI Plugin enabled. 'false' to make it disabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The license of the UI Plugin
	License *string `json:"license,omitempty" tf:"license,omitempty"`

	// The website of the UI Plugin
	Link *string `json:"link,omitempty" tf:"link,omitempty"`

	// The UI Plugin name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Absolute or relative path to the ZIP file containing the UI Plugin
	PluginPath *string `json:"pluginPath,omitempty" tf:"plugin_path,omitempty"`

	// This value is calculated automatically on create by reading the UI Plugin ZIP file contents. You can updateit to `true` to make it provider scoped or `false` otherwise
	ProviderScoped *bool `json:"providerScoped,omitempty" tf:"provider_scoped,omitempty"`

	// The status of the UI Plugin
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// Set of organization IDs to which this UI Plugin must be published
	TenantIds []*string `json:"tenantIds,omitempty" tf:"tenant_ids,omitempty"`

	// This value is calculated automatically on create by reading the UI Plugin ZIP file contents. You can updateit to `true` to make it tenant scoped or `false` otherwise
	TenantScoped *bool `json:"tenantScoped,omitempty" tf:"tenant_scoped,omitempty"`

	// The UI Plugin vendor name
	Vendor *string `json:"vendor,omitempty" tf:"vendor,omitempty"`

	// The version of the UI Plugin
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type UiPluginParameters struct {

	// true to make the UI Plugin enabled. 'false' to make it disabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Absolute or relative path to the ZIP file containing the UI Plugin
	// +kubebuilder:validation:Optional
	PluginPath *string `json:"pluginPath,omitempty" tf:"plugin_path,omitempty"`

	// This value is calculated automatically on create by reading the UI Plugin ZIP file contents. You can updateit to `true` to make it provider scoped or `false` otherwise
	// +kubebuilder:validation:Optional
	ProviderScoped *bool `json:"providerScoped,omitempty" tf:"provider_scoped,omitempty"`

	// Set of organization IDs to which this UI Plugin must be published
	// +kubebuilder:validation:Optional
	TenantIds []*string `json:"tenantIds,omitempty" tf:"tenant_ids,omitempty"`

	// This value is calculated automatically on create by reading the UI Plugin ZIP file contents. You can updateit to `true` to make it tenant scoped or `false` otherwise
	// +kubebuilder:validation:Optional
	TenantScoped *bool `json:"tenantScoped,omitempty" tf:"tenant_scoped,omitempty"`
}

// UiPluginSpec defines the desired state of UiPlugin
type UiPluginSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     UiPluginParameters `json:"forProvider"`
}

// UiPluginStatus defines the observed state of UiPlugin.
type UiPluginStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        UiPluginObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// UiPlugin is the Schema for the UiPlugins API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type UiPlugin struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.enabled)",message="enabled is a required parameter"
	Spec   UiPluginSpec   `json:"spec"`
	Status UiPluginStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// UiPluginList contains a list of UiPlugins
type UiPluginList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []UiPlugin `json:"items"`
}

// Repository type metadata.
var (
	UiPlugin_Kind             = "UiPlugin"
	UiPlugin_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: UiPlugin_Kind}.String()
	UiPlugin_KindAPIVersion   = UiPlugin_Kind + "." + CRDGroupVersion.String()
	UiPlugin_GroupVersionKind = CRDGroupVersion.WithKind(UiPlugin_Kind)
)

func init() {
	SchemeBuilder.Register(&UiPlugin{}, &UiPluginList{})
}
