/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VAppNatRulesObservation struct {

	// When enabled translates a virtual machine's private, internal IP address to a public IP address for outbound traffic.
	EnableIPMasquerade *bool `json:"enableIpMasquerade,omitempty" tf:"enable_ip_masquerade,omitempty"`

	// Enable or disable NAT service. Default is `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// One of: `ipTranslation` (use IP translation), `portForwarding` (use port forwarding).
	NATType *string `json:"natType,omitempty" tf:"nat_type,omitempty"`

	// vApp network identifier
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	Rule []VAppNatRulesRuleObservation `json:"rule,omitempty" tf:"rule,omitempty"`

	// vApp identifier
	VappID *string `json:"vappId,omitempty" tf:"vapp_id,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type VAppNatRulesParameters struct {

	// When enabled translates a virtual machine's private, internal IP address to a public IP address for outbound traffic.
	// +kubebuilder:validation:Optional
	EnableIPMasquerade *bool `json:"enableIpMasquerade,omitempty" tf:"enable_ip_masquerade,omitempty"`

	// Enable or disable NAT service. Default is `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// One of: `ipTranslation` (use IP translation), `portForwarding` (use port forwarding).
	// +kubebuilder:validation:Optional
	NATType *string `json:"natType,omitempty" tf:"nat_type,omitempty"`

	// vApp network identifier
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// +kubebuilder:validation:Optional
	Rule []VAppNatRulesRuleParameters `json:"rule,omitempty" tf:"rule,omitempty"`

	// vApp identifier
	// +kubebuilder:validation:Optional
	VappID *string `json:"vappId,omitempty" tf:"vapp_id,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	// +kubebuilder:validation:Optional
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type VAppNatRulesRuleObservation struct {

	// External IP address to forward to or External IP address to map to VM
	ExternalIP *string `json:"externalIp,omitempty" tf:"external_ip,omitempty"`

	// External port to forward.
	ExternalPort *float64 `json:"externalPort,omitempty" tf:"external_port,omitempty"`

	// Internal port to forward.
	ForwardToPort *float64 `json:"forwardToPort,omitempty" tf:"forward_to_port,omitempty"`

	// ID of the rule. Can be used to track syslog messages.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Mapping mode. One of: `automatic`, `manual`
	MappingMode *string `json:"mappingMode,omitempty" tf:"mapping_mode,omitempty"`

	// Protocol to forward. One of: `TCP` (forward TCP packets), `UDP` (forward UDP packets), `TCP_UDP` (forward TCP and UDP packets).
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// VM to which this rule applies.
	VMID *string `json:"vmId,omitempty" tf:"vm_id,omitempty"`

	// VM NIC ID to which this rule applies.
	VMNicID *float64 `json:"vmNicId,omitempty" tf:"vm_nic_id,omitempty"`
}

type VAppNatRulesRuleParameters struct {

	// External IP address to forward to or External IP address to map to VM
	// +kubebuilder:validation:Optional
	ExternalIP *string `json:"externalIp,omitempty" tf:"external_ip,omitempty"`

	// External port to forward.
	// +kubebuilder:validation:Optional
	ExternalPort *float64 `json:"externalPort,omitempty" tf:"external_port,omitempty"`

	// Internal port to forward.
	// +kubebuilder:validation:Optional
	ForwardToPort *float64 `json:"forwardToPort,omitempty" tf:"forward_to_port,omitempty"`

	// Mapping mode. One of: `automatic`, `manual`
	// +kubebuilder:validation:Optional
	MappingMode *string `json:"mappingMode,omitempty" tf:"mapping_mode,omitempty"`

	// Protocol to forward. One of: `TCP` (forward TCP packets), `UDP` (forward UDP packets), `TCP_UDP` (forward TCP and UDP packets).
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// VM to which this rule applies.
	// +kubebuilder:validation:Required
	VMID *string `json:"vmId" tf:"vm_id,omitempty"`

	// VM NIC ID to which this rule applies.
	// +kubebuilder:validation:Required
	VMNicID *float64 `json:"vmNicId" tf:"vm_nic_id,omitempty"`
}

// VAppNatRulesSpec defines the desired state of VAppNatRules
type VAppNatRulesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VAppNatRulesParameters `json:"forProvider"`
}

// VAppNatRulesStatus defines the observed state of VAppNatRules.
type VAppNatRulesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VAppNatRulesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// VAppNatRules is the Schema for the VAppNatRuless API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type VAppNatRules struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.natType)",message="natType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.networkId)",message="networkId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.vappId)",message="vappId is a required parameter"
	Spec   VAppNatRulesSpec   `json:"spec"`
	Status VAppNatRulesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VAppNatRulesList contains a list of VAppNatRuless
type VAppNatRulesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VAppNatRules `json:"items"`
}

// Repository type metadata.
var (
	VAppNatRules_Kind             = "VAppNatRules"
	VAppNatRules_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VAppNatRules_Kind}.String()
	VAppNatRules_KindAPIVersion   = VAppNatRules_Kind + "." + CRDGroupVersion.String()
	VAppNatRules_GroupVersionKind = CRDGroupVersion.WithKind(VAppNatRules_Kind)
)

func init() {
	SchemeBuilder.Register(&VAppNatRules{}, &VAppNatRulesList{})
}
