/*
Copyright 2023 ANKASOFT
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type VmInternalDiskObservation_2 struct {

	// Powers off VM when changing any attribute of an IDE disk or unit/bus number of other disk types, after the change is complete VM is powered back on. Without this setting enabled, such changes on a powered-on VM would fail.
	AllowVMReboot *bool `json:"allowVmReboot,omitempty" tf:"allow_vm_reboot,omitempty"`

	// The number of the SCSI or IDE controller itself.
	BusNumber *float64 `json:"busNumber,omitempty" tf:"bus_number,omitempty"`

	// The type of disk controller. Possible values: ide, parallel( LSI Logic Parallel SCSI), sas(LSI Logic SAS (SCSI)), paravirtual(Paravirtual (SCSI)), sata, nvme
	BusType *string `json:"busType,omitempty" tf:"bus_type,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies the IOPS for the disk.
	Iops *float64 `json:"iops,omitempty" tf:"iops,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// The size of the disk in MB.
	SizeInMb *float64 `json:"sizeInMb,omitempty" tf:"size_in_mb,omitempty"`

	// Storage profile to override the VM default one
	StorageProfile *string `json:"storageProfile,omitempty" tf:"storage_profile,omitempty"`

	// Specifies whether the disk storage is pre-allocated or allocated on demand.
	ThinProvisioned *bool `json:"thinProvisioned,omitempty" tf:"thin_provisioned,omitempty"`

	// The device number on the SCSI or IDE controller of the disk.
	UnitNumber *float64 `json:"unitNumber,omitempty" tf:"unit_number,omitempty"`

	// VM in vApp in which internal disk is created
	VMName *string `json:"vmName,omitempty" tf:"vm_name,omitempty"`

	// The vApp this VM internal disk belongs to
	VappName *string `json:"vappName,omitempty" tf:"vapp_name,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

type VmInternalDiskParameters_2 struct {

	// Powers off VM when changing any attribute of an IDE disk or unit/bus number of other disk types, after the change is complete VM is powered back on. Without this setting enabled, such changes on a powered-on VM would fail.
	// +kubebuilder:validation:Optional
	AllowVMReboot *bool `json:"allowVmReboot,omitempty" tf:"allow_vm_reboot,omitempty"`

	// The number of the SCSI or IDE controller itself.
	// +kubebuilder:validation:Optional
	BusNumber *float64 `json:"busNumber,omitempty" tf:"bus_number,omitempty"`

	// The type of disk controller. Possible values: ide, parallel( LSI Logic Parallel SCSI), sas(LSI Logic SAS (SCSI)), paravirtual(Paravirtual (SCSI)), sata, nvme
	// +kubebuilder:validation:Optional
	BusType *string `json:"busType,omitempty" tf:"bus_type,omitempty"`

	// Specifies the IOPS for the disk.
	// +kubebuilder:validation:Optional
	Iops *float64 `json:"iops,omitempty" tf:"iops,omitempty"`

	// The name of organization to use, optional if defined at provider level. Useful when connected as sysadmin working across different organizations
	// +kubebuilder:validation:Optional
	Org *string `json:"org,omitempty" tf:"org,omitempty"`

	// The size of the disk in MB.
	// +kubebuilder:validation:Optional
	SizeInMb *float64 `json:"sizeInMb,omitempty" tf:"size_in_mb,omitempty"`

	// Storage profile to override the VM default one
	// +kubebuilder:validation:Optional
	StorageProfile *string `json:"storageProfile,omitempty" tf:"storage_profile,omitempty"`

	// The device number on the SCSI or IDE controller of the disk.
	// +kubebuilder:validation:Optional
	UnitNumber *float64 `json:"unitNumber,omitempty" tf:"unit_number,omitempty"`

	// VM in vApp in which internal disk is created
	// +kubebuilder:validation:Optional
	VMName *string `json:"vmName,omitempty" tf:"vm_name,omitempty"`

	// The vApp this VM internal disk belongs to
	// +kubebuilder:validation:Optional
	VappName *string `json:"vappName,omitempty" tf:"vapp_name,omitempty"`

	// The name of VDC to use, optional if defined at provider level
	// +kubebuilder:validation:Optional
	Vdc *string `json:"vdc,omitempty" tf:"vdc,omitempty"`
}

// VmInternalDiskSpec defines the desired state of VmInternalDisk
type VmInternalDiskSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     VmInternalDiskParameters_2 `json:"forProvider"`
}

// VmInternalDiskStatus defines the observed state of VmInternalDisk.
type VmInternalDiskStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VmInternalDiskObservation_2 `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// VmInternalDisk is the Schema for the VmInternalDisks API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vcd}
type VmInternalDisk struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.busNumber)",message="busNumber is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.busType)",message="busType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.sizeInMb)",message="sizeInMb is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.unitNumber)",message="unitNumber is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.vappName)",message="vappName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.vmName)",message="vmName is a required parameter"
	Spec   VmInternalDiskSpec   `json:"spec"`
	Status VmInternalDiskStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VmInternalDiskList contains a list of VmInternalDisks
type VmInternalDiskList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VmInternalDisk `json:"items"`
}

// Repository type metadata.
var (
	VmInternalDisk_Kind             = "VmInternalDisk"
	VmInternalDisk_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VmInternalDisk_Kind}.String()
	VmInternalDisk_KindAPIVersion   = VmInternalDisk_Kind + "." + CRDGroupVersion.String()
	VmInternalDisk_GroupVersionKind = CRDGroupVersion.WithKind(VmInternalDisk_Kind)
)

func init() {
	SchemeBuilder.Register(&VmInternalDisk{}, &VmInternalDiskList{})
}
