apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "user": "vcd_user",
      "password": "vcd_password",
      "auth_type": "integrated",
      "org": "org",
      "vdc": "vdc",
      "url": "url"
    }
